feat: add useCookieState hook
imbhargav5/rooks pull request #487
Opened 2021-05-15 01:14 UTC by iampika

2021-05-15 06:11 UTC, imbhargav5 requested changes
Also it would be great if we support this syntax as well. https://github.com/js-cookie/js-cookie#read

2021-05-15 06:11 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +    (newValue: string, options?: Cookies.CookieAttributes) => {
The `options` here are best passed at `useCookie` level. 

```jsx
const [] = useCookie('my-cookie', options)
```

2021-05-15 06:11 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +const useCookieState = (
JSDoc comments are missing. We need to add them here :D

2021-05-15 06:11 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +    () => Cookies.get(cookieName) || null
`Get` should also use the same options that were used in `set`

2021-05-15 06:11 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +    () => Cookies.get(cookieName) || null
Als this breaks on the server side. So on the server side we need to return null if window is not defined.

2021-05-15 06:11 UTC, imbhargav5 commented
Looking good overall @iampika Great work!

2021-05-17 07:27 UTC, imbhargav5 requested changes

2021-05-17 07:27 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +const useCookieState = (
So some comments are still missing. You can refer to the other hooks for guidance. Basically we need `useCookie` and also the description of what this hook does in there as well

2021-05-17 07:27 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +    () => Cookies.get(cookieName, options) || cookieValue
We need to check for `window` here. so 

```
const [value, setValue] = useState<string | null>(
     () => {
   if(typeof window !== 'null'){
      return Cookies.get(cookieName, options) || cookieValue
   }else{
      return null;
   }
});
```

2021-05-17 07:27 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +  if (!window) return null;
We don't need window check here.

2021-05-19 07:51 UTC, imbhargav5 requested changes

2021-05-19 07:51 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> + *
We need more comments here.

2021-05-19 07:51 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +
We need useCookieState to listen for updates to this cookie from external events. So basically a listener on cookie change similar to how our useLocalstorageState works. WE need something for cookies .

2021-05-19 07:58 UTC, imbhargav5 requested changes

2021-05-19 07:58 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +  return { deleteCookie, updateCookie, value };
`[value, setValue, removeValue]`

2021-05-19 08:08 UTC, imbhargav5 requested changes

2021-05-19 08:08 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +  cookieValue: string | null = null,
Rename to `key` & 'initialState'.

2021-05-19 08:08 UTC, imbhargav5 commented on src/hooks/useCookieState.ts
> +): UseCookieStateType => {
4th argument JSCookie arguments. At least have `converter` option.

2021-11-14 08:25 UTC, qiweiii commented
@imbhargav5 Seems ready to merge after sovling conflicts

2022-06-30 08:00 UTC, closed without merging