feat: useResizeObserver hook
imbhargav5/rooks pull request #503
Opened 2021-06-21 06:42 UTC by AdrienLemaire

Recreated the PR #502 using the main branch.

> Inspired by the existing [useMutationObserver](https://react-hooks.org/docs/useMutationObserver), I wrote a similar hook using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) and thought this might be a useful addition to the library.

2021-07-02 11:20 UTC, imbhargav5 commented
Hey @AdrienLemaire the build seems to be failing. Perhaps some types broke.

2021-07-02 11:37 UTC, AdrienLemaire commented
@imbhargav5 please consider upgrading the typescript dependency version for rooks.
I cannot see ResizeObserver in 4.0.5, but my project using typescript 4.3.4 is correctly typed:

https://github.com/microsoft/TypeScript/blob/v4.3.4/lib/lib.dom.d.ts#L12515

2021-07-02 11:40 UTC, imbhargav5 commented
Gotcha. Looks like I have a big weekend in front of me 😂

2021-07-21 12:16 UTC, imbhargav5 commented
/rebase

2021-07-21 12:20 UTC, imbhargav5 requested changes

2021-07-21 12:20 UTC, imbhargav5 commented on src/hooks/useResizeObserver.ts
> +  }, [ref.current]); // eslint-disable-line react-hooks/exhaustive-deps
Using `Ref`.current with `useEffect` won't work. Instead we should use callback refs.

2022-08-03 23:38 UTC, closed without merging