Feat use resize observer
imbhargav5/rooks pull request #523
Opened 2021-07-26 15:44 UTC by qiweiii

Continue from #503

2021-08-14 06:10 UTC, imbhargav5 requested changes

2021-08-14 06:10 UTC, imbhargav5 commented on src/hooks/useResizeObserver.ts
> +function useResizeObserver(
I think I want to get away from the pattern of using `mutableRef`s here and instead use `Callback` refs. Also let's change this hook to be `useResizeObserverRef` and create a ref in the hook and then expose it out. 

```jsx
const [ref] = useResizeObserver(callback, options)

<div ref={ref}>

</div>
```

2021-08-14 06:12 UTC, imbhargav5 commented on src/hooks/useResizeObserver.ts
> +function useResizeObserver(
Main reason for it being that `mutableRefs` don't really track node changes. Apologies for not mentioning this in advance but this is a better solution in the long run and I would appreciate this change a lot! @qiweiii

2021-08-14 17:44 UTC, imbhargav5 commented on src/hooks/useResizeObserverRef.ts
> +interface ResizeObserverOptions {
Instead of using types from here, are there types from ResizeObserver natively somewhere? Just a thought.

2021-08-14 17:46 UTC, imbhargav5 requested changes

2021-08-14 17:46 UTC, imbhargav5 commented on src/hooks/useResizeObserverRef.ts
> +  }, [node, callback, options]);
We will need to use `useFreshTick` here, which will keep the callback fresh. https://react-hooks.org/docs/useFreshTick

Let's also add tests for this one. Excellent work so far! @qiweiii

2021-08-15 04:37 UTC, qiweiii commented on src/__tests__/useResizeObserverRef.spec.tsx
> +});
Since jsDOM not supporting layout code like ResizeObserver or MutationObserver, so I cannot test behaviour of this hook

2022-08-03 23:38 UTC, closed without merging

2022-08-03 23:38 UTC, imbhargav5 commented
Your commits were released in another PR. Thanks @qiweiii !